### ISSUE TITLE
 Cannot resolve dependencyエラーでビルドがこけてしまう

### ISSUE THREAD

**Issue by Apryl-ym** [iMasanari/mhw-simulator#63]
ご覧になられているか分かりませんがイシューさせて頂きます。
線形計画法に基づいて実装されているスキルシミュを分析させて頂きたく、このプロジェクトをローカルにclone後、
`npm install`, `npm run dev`をした結果、ビルドでこけてしまうのでご助力頂きたく書き込ませて頂きました。

`npm run dev`後に出力されるログで目立って気になるのは以下の2項目で、
generateにて何らかの問題で必要なjsonファイルが生成されずにエラーとなっているようです。

```
> mhw-simulator@1.0.0 scripts:generate I:\MyFiles\MyServer\Projects\mhw-simulator
> ts-node -P tsconfig.ts-node.json scripts/generate.ts

(node:14624) ExperimentalWarning: The fs.promises API is experimental
(node:14624) UnhandledPromiseRejectionWarning: TypeError: group.match is not a function or its return value is not iterable
    at fromEntries_1.default.txt.split.map.group (I:\MyFiles\MyServer\Projects\mhw-simulator\scripts\generate\armorGroup.ts:14:40)
    at Array.map (<anonymous>)
    at I:\MyFiles\MyServer\Projects\mhw-simulator\scripts\generate\armorGroup.ts:13:21
    at Generator.next (<anonymous>)
    at fulfilled (I:\MyFiles\MyServer\Projects\mhw-simulator\scripts\generate\armorGroup.ts:5:58)
(node:14624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (
rejection id: 1)
(node:14624) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
Server running at http://localhost:1234 
×  I:\MyFiles\MyServer\Projects\mhw-simulator\src\app\util\generatedUtil.ts:7:26: Cannot resolve dependency '~/generated/charm.json' at 'I:\MyFiles\MyServer\Projects\mhw-simulator\src\app\util\~\generated\charm.json'
    at Resolver.resolve (I:\MyFiles\MyServer\Projects\mhw-simulator\node_modules\parcel-bundler\src\Resolver.js:71:17)
```

初歩的な内容でしたら大変恐縮ではありますが、
何か気になる点があればご助言よろしくお願いいたします。

**Comment by iMasanari** [comment]
@Apryl-ym さん

このリポジトリに興味を持っていただき、ありがとうございます。
拙いコードではありますが、ご参考になればと思います。

> generateにて何らかの問題で必要なjsonファイルが生成されずにエラーとなっているようです。

ご報告いただいた通り、jsonファイル生成に失敗しているものと思われます。

`lib/armorGroup.txt`に、空白行や末尾の改行がないことを確認してください。（特に、末尾の改行はエディタなどの自動フォーマットで勝手に追加されている可能性があります）
[エラー該当箇所のコード][code]を確認したところ、データのない行(改行のみなど)がある場合にご報告いただいたエラーが発生することを確認しました。

もしくは、次のように、データのない行を無視するようコードを書き換えても動くようになると思います。

```diff
 // scripts/generate/armorGroup.ts
   const result = fromEntries(
-    txt.split('\n').map(group => {
+    txt.split('\n').filter(Boolean).map(group => {
       const [_, prefix, safix] = group.match(/^(.+?)([αβγ]?)$/)!
       const equips = armors.map(list => findArmor(list, prefix, safix))
 
       return [group, equips]
     })
   )
```

もし、上記で解決できない場合、生成済みのjsonデータをお渡ししますので、ご連絡いただけたらと思います。

[code]: https://github.com/iMasanari/mhw-simulator/blob/fd65449574a6f7b25efd3af800c2d585708188df/scripts/generate/armorGroup.ts#L14

**Comment by Apryl-ym** [comment]
@iMasanari さん

返信頂きありがとうございます。

libに配置されている各種`.txt` `.csv`の空白や改行について確認した上、
> もしくは、次のように、データのない行を無視するようコードを書き換えても動くようになると思います。

こちらの修正も加えてみたのですが結果は変わらずでした。

大変お手数ではございますが、
`src/generated`に生成される各種ファイル一式を頂いてもよろしいでしょうか？
ちなみにですが現状、生成に上手くいっているのは以下の9ファイルになります。

```
allSkill.json
arm.json
body.json
head.json
leg.json
oneset.json
seriesSkill.json
skillList.json
wst.json
```

よろしくお願いいたします。

**Comment by iMasanari** [comment]
生成ファイルをお送りいたします。

[generated.zip](https://github.com/iMasanari/mhw-simulator/files/5814127/generated.zip)

上記zipを展開、`src/generated`に配置し、下記ファイルを編集することで動くと思います。

```diff
// package.json
   "scripts": {
     "clean": "rimraf dist src/generated",
     "copy": "npm run copy:static && npm run copy:wasm",
     "copy:static": "cpx static/* dist/",
     "copy:wasm": "cpx node_modules/glpk.js/glpk.wasm dist/",
     "scripts:generate": "ts-node -P tsconfig.ts-node.json scripts/generate.ts",
     "scripts:fetch": "ts-node -P tsconfig.ts-node.json scripts/fetch.ts",
     "postscripts:fetch": "npm run scripts:generate",
-    "prebuild": "npm run clean && npm run scripts:generate && npm run copy",
+    "prebuild": "npm run clean && npm run copy",
     "build": "parcel build src/index.html --public-url https://imasanari.github.io/mhw-simulator/",
     "predev": "npm run prebuild",
     "dev": "parcel src/index.html",
     "i18next-extract": "NODE_ENV=development babel --config-file ./i18next-extract.babelrc './src/**/*.{js,jsx,ts,tsx}' > /dev/null",
     "test": "tsc -p . --noEmit"
   },
```

**Comment by Apryl-ym** [comment]
@iMasanari 

生成ファイル一式ありがとうございました。

package.json内のprebuildですが、npm run cleanがgeneratedディレクトリを削除してしまうので、
このコマンドだけ取り除き以下のようにすることで無事ビルドが通りました。

```
"prebuild": "npm run copy",
```

サイトも正常に表示され、検索も問題なく動作いたしました。
非常に助かりました、本当にありがとうございました。

**Comment by iMasanari** [comment]
動作してよかったです。

勝手ではありますが、issueは「再現不可」としてcloseさせていただきます。
エラーの心当たりを見つけたり、他の不具合を発見したりした場合は、このissueや新規issueで報告いただけたらと思います。
